apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: {{ServiceName}} 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ServiceName}} 
    spec:
      containers:
        - name: {{ServiceName}}
          env:
          - name: ASPNETCORE_URLS
            value: http://+:8080
          - name: Logging__MinimumLevel 
            value: Error 
          - name: Orleans__MembershipProvider__Name
            value: Kubernetes
          - name: Orleans__Streams__Kafka__Brokers
            value: cp-kafka:9092
          image: fluffyspoon.azurecr.io/{{ServiceName}}
          ports:
          - containerPort: 8080
          livenessProbe:
              httpGet:
                  path: actuator/health/live
                  port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
          readinessProbe:
              httpGet:
                  path: actuator/health/ready
                  port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10