version: '3.4'

services:
  {{ServiceName}}:
    image: fluffyspoon.template
    build:
      dockerfile: src/fluffyspoon.template/Dockerfile
      context: ..
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - Orleans__MembershipProvider__Address=http://consul:8500
      - Orleans__Streams__Kafka__Brokers=kafka:9092
    ports:
      - "5005:8080"
    depends_on:
      - consul
      - kafka
    restart: on-failure

  consul:
    image: consul:latest
    command: "agent -server -bootstrap -ui -client 0.0.0.0"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    restart: on-failure

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.3.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - kafka
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021